#ifndef ch06_branching_statements_n_logical_operators_hpp
#define ch06_branching_statements_n_logical_operators_hpp

int ch06_branching_statements_n_logical_operators();

#endif /* ch06_branching_statements_n_logical_operators_hpp */
